### ISSUE TITLE
Show indicator on click

### ISSUE THREAD

**Issue by ssshake** [RaptorCalculus/mars-endeavour#30]
Underground navigation would be better if we just spawn a circle similar to what happends when you click on a robot, where you click to move to when underground. Instantiate it and set a Destroy(gameObject, 3f);

**Comment by AngelinaLapteva** [comment]
I can draw a nice indicator when robot is chosen
How about that?

**Comment by ssshake** [comment]
I actually already did this. See the small videos I posted in the general chat. If you want to make a texture that looks better than a solid color circle that could work.

**Comment by AngelinaLapteva** [comment]
Can we leave an indicator on choosen robot till we didn't click another one? or takes too much time?

**Comment by ssshake** [comment]
Not sure what you mean.

Currently when you click a robot there is a high under it.. It stays there until you click on something else

**Comment by AngelinaLapteva** [comment]
oh good then
